apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: radix-image-builder
  annotations:
    github.com/project-slug: equinor/radix-image-builder
spec:
  type: other
  lifecycle: unknown
  owner: omnia-radix
