name: radix-image-builder-build
on:
  push:
    branches:
      - master
      - release
permissions:
  id-token: write
jobs:
  build-deploy-image-dev:
    name: Build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
      - run: |
          docker build . -t radixdev.azurecr.io/radix-image-builder:${GITHUB_REF##*/}-latest -t radixprod.azurecr.io/radix-image-builder:${GITHUB_REF##*/}-latest -t radixus.azurecr.io/radix-image-builder:${GITHUB_REF##*/}-latest
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - name: 'Login to ACR radixdev'
        run: |
          az acr login --name radixdev
      - name: 'Push to radixdev'
      - run: |
          docker push radixdev.azurecr.io/radix-image-builder:${GITHUB_REF##*/}-latest
  build-deploy-image-prod:
    if: github.ref == 'refs/heads/release'
    name: Build-push
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_PROD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}
      - name: 'Login to ACR radixprod'
        run: |
          az acr login --name radixprod
      - name: 'Push to radixprod'
      - run: |
          docker push radixprod.azurecr.io/radix-image-builder:${GITHUB_REF##*/}-latest
