name: Build and deploy Docker
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # semver stable
      - 'v[0-9]+.[0-9]+.[0-9]+-*' # semver with prerelease suffix
jobs:
  metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.metadata.outputs.version }}
      release-exist: ${{ steps.metadata.outputs.release_exist }}
    steps:
      - uses: actions/checkout@v4
      - name: Metadata
        id: metadata
        env:
          tag: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -Eeuo pipefail

          version=${tag#v}
          release_exist="true"

          if ! gh release view v${version} 1> /dev/null ; then
            release_exist="false"
          fi

          echo "version="$version"" >>"$GITHUB_OUTPUT"
          echo "release_exist="$release_exist"" >>"$GITHUB_OUTPUT"
          
  deploy-docker:
    runs-on: ubuntu-latest
    needs: metadata
    permissions:
      contents: read
      packages: write
    env:
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - name: Container metadata
        id: container-metadata
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.CONTAINER_REGISTRY }}/equinor/radix/image-builder"
          tags: ${{ needs.metadata.outputs.version }}
      - name: Build and push container images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: ${{ steps.container-metadata.outputs.tags }}
          labels: ${{ steps.container-metadata.outputs.labels }}
