name: Pull Request
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: pull-request-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        platforms: |
          linux/amd64
          linux/arm64
